services:
    postgres:
        image: postgres:15
        container_name: express_postgres
        restart: always
        environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: changeinprod
        POSTGRES_DB: bactphagesgraph
        ports:
        - "5432:5432"
        volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 